#!/usr/bin/env ruby
tomcat_port = ARGV[0]
tomcat_host = ARGV[1]
app_name = ARGV[2]
exit 1 unless tomcat_port && tomcat_host && app_name

NUXEO_CONF = "nuxeo/bin/nuxeo.conf"
content = File.read(NUXEO_CONF)

File.open(NUXEO_CONF, "w") {
  |file| file.puts content.gsub(/TCATPORT/, tomcat_port).gsub(/TCATHOST/, tomcat_host).gsub(/APPNAME/, app_name)
}
