#!/usr/bin/env ruby
tomcat_port = ARGV[0]
tomcat_host = ARGV[1]
fqdn = ARGV[3]
exit 1 unless tomcat_port && tomcat_host && fqdn

NUXEO_CONF = "nuxeo/conf/nuxeo.conf"
content = File.read(NUXEO_CONF)

File.open(NUXEO_CONF, "w") {
  |file| file.puts content.gsub(/TCATPORT/, tomcat_port).gsub(/TCATHOST/, tomcat_host).gsub(/FQDN/, fqdn)
}
